[project]
name = "fileanalysis"
version = "0.1.0"
description = "This project can analyze the csv, excel and make the insight report"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
]
